### ISSUE TITLE
Scroller doesn't work with <!DOCTYPE html>

### ISSUE THREAD

**Issue by vrushank** [malihu/thumbnail-scroller#12]
I was trying to create a vertical content scroller with <!DOCTYPE html>.

It doesn't work. Removing <!DOCTYPE html> work perfectly. Can you let me know the reason behind this behaviour?

**Comment by malihu** [comment]
Hi, 

All plugin demos and examples of the plugin are using the `<!DOCTYPE html>` (you can see them all here: https://github.com/malihu/thumbnail-scroller/tree/master/examples), so I'm not sure why you have such issue in your implementation(?) Do you get any console erros?

**Comment by vrushank** [comment]
Thanks for quick response. Never mind, I had two parent divs for menu. Removing one resolved my issue.

Thanks a lot for great plugin.
