### ISSUE TITLE
hover button

### ISSUE THREAD

**Issue by bigboss234** [malihu/thumbnail-scroller#7]
Hi please how can i use a external buttons onhover to scroll the slider and disable the edges hotspot scrolling

**Comment by malihu** [comment]
Hello, 

You basically need to set `type:"hover-100"` to remove edges hotspots and use plugin's _scrollTo_ and _stop_ methods on your custom buttons. 

Using the methods without intervals, setting scrolling speed according to content length etc. requires some additional calculations. For convenience, I've created an example that does all the above and is pretty much ready to use, so check it and grab the code: 

http://manos.malihu.gr/repository/jquery-thumbnail-scroller/demo/examples/hover-buttons-test.html

**Comment by bigboss234** [comment]
Thank you so much, works like a charme

**Comment by malihu** [comment]
You're welcome :)
