### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by khantroversy** [malihu/thumbnail-scroller#8]
can you help me with lazy load with this plugin

**Comment by malihu** [comment]
Hi, 

I have such a demo here: 
http://manos.malihu.gr/repository/jquery-thumbnail-scroller/demo/examples/lazy-load-images-demo.html

You can view its source and get the code, markup and CSS.

**Comment by khantroversy** [comment]
tried it, but its not working on my end, 

if($this.attr("src").indexOf("blank.gif")!==-1 && $this.is(":mtsInView")){
              //console.log('enter');
              imgLoader($this,$this.attr("data-src"));

```
        }
```

::mtsInView condition is not met, hence it doesn't replace the img src with data-src, scroller is working, no lazy loading, there is no console error

**Comment by khantroversy** [comment]
lazy load working now with following callback option

whileScrolling: function() {  
        $("img.lazy").lazyload();
}
