### ISSUE TITLE
How to auto-scroll...

### ISSUE THREAD

**Issue by sieulog** [malihu/thumbnail-scroller#9]
Hello everyone,

How to auto-scroll?. Users shouldn't hover to items.

**Comment by malihu** [comment]
Hello, 

There's an [auto-scroll example](https://github.com/malihu/thumbnail-scroller/blob/master/examples/auto_scroll_example.html) in the archive. 

Not sure what you mean by "Users shouldn't hover to items". You can use the scroller with scrolling buttons if you don't want hover - [see type option](http://manos.malihu.gr/jquery-thumbnail-scroller/#plugin-data-type).

**Comment by sieulog** [comment]
I want auto-scroll.

I will try with link you give to me. Thank you so much!
